"use client"

/**
 * BenchmarkExportButton — EXP-1c
 *
 * Button that sends the full BenchmarkResult to the backend via POST
 * and downloads the generated Excel as a blob.
 *
 * The benchmark lives in frontend memory only (no Supabase job_id), so
 * we POST the entire result to POST /api/forecast/benchmark/export.
 *
 * Excel structure (generated by BenchmarkExporter):
 *   Sheet 1 — Comparación: all models with WAPE/MAE/BIAS/RMSE/FVA + color semaphores
 *   Sheet 2 — Conclusión: winner, FVA interpretation guide (Vandeputt)
 *   Sheet N — Pred <model>: future predictions per model
 */

import { useState } from "react"
import Button from "@mui/material/Button"
import CircularProgress from "@mui/material/CircularProgress"
import Tooltip from "@mui/material/Tooltip"
import Snackbar from "@mui/material/Snackbar"
import Alert from "@mui/material/Alert"
import FileDownloadIcon from "@mui/icons-material/FileDownload"
import type { BenchmarkResult } from "@/lib/types"

interface BenchmarkExportButtonProps {
  benchmarkResult: BenchmarkResult
}

export function BenchmarkExportButton({ benchmarkResult }: BenchmarkExportButtonProps) {
  const [loading, setLoading]     = useState(false)
  const [successMsg, setSuccess]  = useState(false)
  const [errorMsg, setError]      = useState<string | null>(null)

  const handleExport = async () => {
    setLoading(true)
    setError(null)
    try {
      // POST the full BenchmarkResult — backend returns xlsx as blob
      const response = await fetch("/api/forecast/benchmark/export", {
        method:  "POST",
        headers: { "Content-Type": "application/json" },
        body:    JSON.stringify(benchmarkResult),
      })

      if (!response.ok) {
        const text = await response.text()
        throw new Error(text || `Error ${response.status}`)
      }

      // Native blob download — no page navigation
      const blob     = await response.blob()
      const url      = URL.createObjectURL(blob)
      const slug     = benchmarkResult.dataset_id?.slice(0, 12) ?? "benchmark"
      const filename = `forecastiq_benchmark_${slug}.xlsx`

      const a = document.createElement("a")
      a.href     = url
      a.download = filename
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)

      setSuccess(true)
    } catch (err) {
      setError(err instanceof Error ? err.message : "Error al exportar el benchmark")
    } finally {
      setLoading(false)
    }
  }

  return (
    <>
      <Tooltip title="Exportar comparación de modelos como Excel analítico (métricas + semáforos + predicciones)">
        <span>
          <Button
            variant="outlined"
            size="small"
            color="secondary"
            startIcon={
              loading
                ? <CircularProgress size="0.875rem" color="inherit" />
                : <FileDownloadIcon />
            }
            onClick={handleExport}
            disabled={loading}
            sx={{ fontSize: "0.75rem", whiteSpace: "nowrap" }}
          >
            {loading ? "Exportando…" : "Exportar benchmark"}
          </Button>
        </span>
      </Tooltip>

      {/* Success toast */}
      <Snackbar
        open={successMsg}
        autoHideDuration={3000}
        onClose={() => setSuccess(false)}
        anchorOrigin={{ vertical: "bottom", horizontal: "center" }}
      >
        <Alert severity="success" onClose={() => setSuccess(false)} sx={{ fontSize: "0.8125rem" }}>
          Excel del benchmark descargado correctamente.
        </Alert>
      </Snackbar>

      {/* Error toast */}
      <Snackbar
        open={!!errorMsg}
        autoHideDuration={5000}
        onClose={() => setError(null)}
        anchorOrigin={{ vertical: "bottom", horizontal: "center" }}
      >
        <Alert severity="error" onClose={() => setError(null)} sx={{ fontSize: "0.8125rem" }}>
          {errorMsg}
        </Alert>
      </Snackbar>
    </>
  )
}
